name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VITE_OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Cache Backend Dependencies
      uses: actions/cache@v3
      with:
        path: backend/node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-backend-

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci

    - name: Run Backend Tests
      run: |
        cd backend
        npm run test:coverage

    - name: Debug Backend Coverage
      run: |
        echo "Checking backend coverage directory..."
        ls -la backend/coverage || echo "Backend coverage directory not found!"
        if [ -d "backend/coverage" ]; then
          echo "Contents of backend/coverage:"
          ls -la backend/coverage
        fi

    - name: Cache Frontend Dependencies
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-frontend-

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci

    - name: Run Frontend Tests
      run: |
        cd frontend
        npm run test:coverage

    - name: Debug Frontend Coverage
      run: |
        echo "Checking frontend coverage directory..."
        ls -la frontend/coverage || echo "Frontend coverage directory not found!"
        if [ -d "frontend/coverage" ]; then
          echo "Contents of frontend/coverage:"
          ls -la frontend/coverage
        fi

    - name: Upload Backend Coverage
      if: success() && exists('backend/coverage')
      uses: actions/upload-artifact@v3
      with:
        name: backend-coverage
        path: backend/coverage
        if-no-files-found: error

    - name: Upload Frontend Coverage
      if: success() && exists('frontend/coverage')
      uses: actions/upload-artifact@v3
      with:
        name: frontend-coverage
        path: frontend/coverage 